services:
  _defaults:
    public: true

  mondialrelay.module:
    class: mondialrelay
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mondialrelay'

  mondialrelay.context:
    class: Context
    factory: ['Context', 'getContext']
