services:
  _defaults:
    public: true

  ##############
  # Your Module

  mondialrelay.module:
    class: mondialrelay
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mondialrelay'

  mondialrelay.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account
  mondialrelay.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  mondialrelay.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@mondialrelay.ps_accounts_installer'